version: "3.9"

services:
  quest-rooms-server:
    image: php:8.1
    container_name: quest-rooms-server
    command: php -S 0.0.0.0:3003
    working_dir: /app
    ports:
      - 3003:3003
    volumes:
      - .:/app
